ALTER DATABASE [%(dbName)s] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [%(dbName)s] SET ANSI_NULLS OFF 
ALTER DATABASE [%(dbName)s] SET ANSI_PADDING OFF 
ALTER DATABASE [%(dbName)s] SET ANSI_WARNINGS OFF 
ALTER DATABASE [%(dbName)s] SET ARITHABORT OFF 
ALTER DATABASE [%(dbName)s] SET AUTO_CLOSE OFF 
ALTER DATABASE [%(dbName)s] SET AUTO_CREATE_STATISTICS OFF 
ALTER DATABASE [%(dbName)s] SET AUTO_SHRINK OFF 
ALTER DATABASE [%(dbName)s] SET AUTO_UPDATE_STATISTICS OFF 
ALTER DATABASE [%(dbName)s] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [%(dbName)s] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [%(dbName)s] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [%(dbName)s] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [%(dbName)s] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [%(dbName)s] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [%(dbName)s] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [%(dbName)s] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [%(dbName)s] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [%(dbName)s] SET READ_WRITE 
ALTER DATABASE [%(dbName)s] SET RECOVERY SIMPLE
ALTER DATABASE [%(dbName)s] SET PAGE_VERIFY CHECKSUM
ALTER DATABASE [%(dbName)s] SET MULTI_USER
ALTER DATABASE [%(dbName)s] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
GO