ALTER DATABASE [%(dbName)s] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [%(dbName)s] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [%(dbName)s] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
ALTER DATABASE [%(dbName)s] SET RECOVERY FULL
ALTER DATABASE [%(dbName)s] SET PAGE_VERIFY TORN_PAGE_DETECTION